version: '3'
services:
    apache_img_1:
        container_name: ${COMPOSE_PROJECT_NAME}_apache1
        build: ./apache/server_1
        ports:
        - 220:80
        
        networks:
            my-network1:
                ipv4_address: ${APACHE_1_IP}
    apache_img_2:
        container_name: ${COMPOSE_PROJECT_NAME}_apache2
        build: ./apache/server_2
        ports:
        - 228:80
        networks:
            my-network1:
                ipv4_address: ${APACHE_2_IP}
        environment:
            - APACHE_1_IP=${APACHE_1_IP}
            - APACHE_2_IP=${APACHE_2_IP}
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
networks:
    my-network1:    
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}